export type LevelId = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
export type LevelDifficulty = "EASY" | "MEDIUM" | "HARD";

export interface LevelDefinition {
  id: LevelId;
  difficulty?: LevelDifficulty;
  isImpossible?: boolean;
  title: string;
  prompt: string;
  hint: string;
  cards: string[];
  acceptedOutput: RegExp;
}

const card = (statement: string) => `      ${statement}`;
const labeledCard = (label: number, statement: string) =>
  `${String(label).padEnd(6, " ")}${statement}`;

export const LEVELS: LevelDefinition[] = [
  {
    id: 1,
    difficulty: "EASY",
    title: "Square of an Integer",
    prompt: "Set N to 4, calculate its square, and print the result.",
    hint: "Use one integer variable for 4, another for its product, and an integer FORMAT statement for the printed result.",
    cards: [
      card("N = 4"),
      card("ISQ = N * N"),
      card("WRITE(6, 20) ISQ"),
      labeledCard(20, "FORMAT(I3)"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*16\s*$/m,
  },
  {
    id: 2,
    difficulty: "EASY",
    title: "Simple Sum",
    prompt: "Set A to 5 and B to 3, add them together, and print the result.",
    hint: "Store 5 and 3 in separate variables, add them into a third variable, then print that value.",
    cards: [
      card("A = 5"),
      card("B = 3"),
      card("C = A + B"),
      card("WRITE(6, 20) C"),
      labeledCard(20, "FORMAT(I3)"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*8\s*$/m,
  },
  {
    id: 3,
    difficulty: "EASY",
    title: "Counting to Five",
    prompt: "Print the numbers 1 through 5 using a DO loop.",
    hint: "Use a DO loop variable that starts at 1 and ends at 5, with a WRITE statement inside the loop.",
    cards: [
      card("DO 10 I = 1, 5"),
      card("WRITE(6, 20) I"),
      labeledCard(20, "FORMAT(I2)"),
      labeledCard(10, "CONTINUE"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*1\s*\r?\n\s*2\s*\r?\n\s*3\s*\r?\n\s*4\s*\r?\n\s*5\s*$/m,
  },
  {
    id: 4,
    difficulty: "EASY",
    title: "Multiplication Table",
    prompt: "Print the first five multiples of 5 using a DO loop.",
    hint: "Loop from 1 through 5, multiply the loop variable by 5, and print the product each iteration.",
    cards: [
      card("DO 10 I = 1, 5"),
      card("M = I * 5"),
      card("WRITE(6, 20) M"),
      labeledCard(20, "FORMAT(I3)"),
      labeledCard(10, "CONTINUE"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*5\s*\r?\n\s*10\s*\r?\n\s*15\s*\r?\n\s*20\s*\r?\n\s*25\s*$/m,
  },
  {
    id: 5,
    difficulty: "EASY",
    title: "Countdown",
    prompt: "Print a countdown from 3 to 1 using a loop and a conditional branch.",
    hint: "Start at 3, print the current value, subtract 1, and branch back while the value remains positive.",
    cards: [
      card("N = 3"),
      labeledCard(10, "WRITE(6, 20) N"),
      labeledCard(20, "FORMAT(I2)"),
      card("N = N - 1"),
      card("IF (N .GT. 0) GO TO 10"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*3\s*\r?\n\s*2\s*\r?\n\s*1\s*$/m,
  },
  {
    id: 6,
    difficulty: "MEDIUM",
    title: "Arithmetic Branching",
    prompt: "Use an arithmetic IF to print EQUAL when N is 4.",
    hint: "Set N to 4 and branch based on N minus 4; the equal branch should print EQUAL.",
    cards: [
      card("N = 4"),
      card("IF (N - 4) 30, 20, 30"),
      labeledCard(20, "WRITE(6, 10)"),
      labeledCard(10, "FORMAT(5HEQUAL)"),
      card("STOP"),
      labeledCard(30, "WRITE(6, 40)"),
      labeledCard(40, "FORMAT(8HUNEQUAL)"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*EQUAL\s*$/m,
  },
  {
    id: 7,
    difficulty: "MEDIUM",
    title: "Powers of Two",
    prompt: "Print the first four powers of two using a DO loop.",
    hint: "Loop I from 1 through 4, calculate 2 to the power of I, and print each result.",
    cards: [
      card("DO 10 I = 1, 4"),
      card("K = 2 ** I"),
      card("WRITE(6, 20) K"),
      labeledCard(20, "FORMAT(I3)"),
      labeledCard(10, "CONTINUE"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*2\s*\r?\n\s*4\s*\r?\n\s*8\s*\r?\n\s*16\s*$/m,
  },
  {
    id: 8,
    difficulty: "MEDIUM",
    title: "Array Accumulator",
    prompt: "Store three numbers in an array, add them, and print the total.",
    hint: "Declare an array with three elements, assign the values, add all three into a total, and print it.",
    cards: [
      card("DIMENSION NUMS(3)"),
      card("NUMS(1) = 10"),
      card("NUMS(2) = 25"),
      card("NUMS(3) = 15"),
      card("TOTAL = NUMS(1) + NUMS(2) + NUMS(3)"),
      card("WRITE(6, 50) TOTAL"),
      labeledCard(50, "FORMAT(F6.1)"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*50(?:\.0+)?\s*$/m,
  },
  {
    id: 9,
    difficulty: "HARD",
    title: "Fibonacci Sequence",
    prompt: "Print the first six numbers in the Fibonacci sequence.",
    hint: "Begin with two 1 values, print them, then repeatedly add the previous two values and shift forward.",
    cards: [
      card("IA = 1"),
      card("IB = 1"),
      card("WRITE(6, 20) IA"),
      card("WRITE(6, 20) IB"),
      card("DO 10 I = 1, 4"),
      card("IC = IA + IB"),
      card("WRITE(6, 20) IC"),
      card("IA = IB"),
      card("IB = IC"),
      labeledCard(10, "CONTINUE"),
      labeledCard(20, "FORMAT(I4)"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*1\s*\r?\n\s*1\s*\r?\n\s*2\s*\r?\n\s*3\s*\r?\n\s*5\s*\r?\n\s*8\s*$/m,
  },
  {
    id: 10,
    difficulty: "HARD",
    title: "Factorial Calculator",
    prompt: "Calculate and print the factorial of 5.",
    hint: "Initialize a product at 1, loop from 1 through 5 multiplying into it, then print the product.",
    cards: [
      card("N = 5"),
      card("IFACT = 1"),
      card("DO 10 I = 1, N"),
      card("IFACT = IFACT * I"),
      labeledCard(10, "CONTINUE"),
      card("WRITE(6, 20) IFACT"),
      labeledCard(20, "FORMAT(I5)"),
      card("STOP"),
      card("END"),
    ],
    acceptedOutput: /^\s*120\s*$/m,
  },
  {
    id: 11,
    isImpossible: true,
    title: "Conway's Game of Life",
    prompt: "Punch the complete 100-card Conway's Game of Life deck: a 6x6 blinker simulated over three generations with IBM JCL wrappers.",
    hint: "This is a larger simulation: initialize a 6x6 grid, place a vertical blinker, count neighbors for each generation, and print every generation.",
    cards: [
      "//SFULIFE  JOB (CMPT101,100),'CONWAY',CLASS=A,MSGLEVEL=(1,1)",
      "//EXEC     FORTRANG,PARM.FORT='NODECK,LOAD'",
      "//FORT.SYSIN DD *",
      card("INTEGER GRID(6,6), NEXT(6,6)"),
      card("INTEGER GEN, ROW, COL, DR, DC, RR, CC, NB, CURR"),
      card("DO 20 ROW = 1, 6"),
      card("DO 10 COL = 1, 6"),
      card("GRID(ROW, COL) = 0"),
      card("NEXT(ROW, COL) = 0"),
      labeledCard(10, "CONTINUE"),
      labeledCard(20, "CONTINUE"),
      card("GRID(3, 4) = 1"),
      card("GRID(4, 4) = 1"),
      card("GRID(5, 4) = 1"),
      card("WRITE(6, 30)"),
      labeledCard(30, "FORMAT(24HCONWAY GAME OF LIFE - SFU)"),
      card("DO 200 GEN = 1, 3"),
      card("WRITE(6, 40) GEN"),
      labeledCard(40, "FORMAT(12H GENERATION , I2)"),
      card("DO 60 ROW = 1, 6"),
      card("WRITE(6, 50) (GRID(ROW, COL), COL = 1, 6)"),
      labeledCard(50, "FORMAT(1X, 6I3)"),
      labeledCard(60, "CONTINUE"),
      card("DO 150 ROW = 1, 6"),
      card("DO 140 COL = 1, 6"),
      card("NB = 0"),
      card("DO 100 DR = -1, 1"),
      card("DO 90 DC = -1, 1"),
      card("IF (DR) 70, 65, 70"),
      labeledCard(65, "IF (DC) 70, 90, 70"),
      labeledCard(70, "RR = ROW + DR"),
      card("CC = COL + DC"),
      card("IF (RR - 1) 90, 75, 75"),
      labeledCard(75, "IF (RR - 6) 80, 80, 90"),
      labeledCard(80, "IF (CC - 1) 90, 85, 85"),
      labeledCard(85, "IF (CC - 6) 88, 88, 90"),
      labeledCard(88, "IF (GRID(RR, CC) - 1) 90, 89, 90"),
      labeledCard(89, "NB = NB + 1"),
      labeledCard(90, "CONTINUE"),
      labeledCard(100, "CONTINUE"),
      card("CURR = GRID(ROW, COL)"),
      card("IF (CURR - 1) 120, 110, 120"),
      labeledCard(110, "IF (NB - 2) 112, 115, 111"),
      labeledCard(111, "IF (NB - 3) 115, 115, 112"),
      labeledCard(112, "NEXT(ROW, COL) = 0"),
      card("GO TO 140"),
      labeledCard(115, "NEXT(ROW, COL) = 1"),
      card("GO TO 140"),
      labeledCard(120, "IF (NB - 3) 122, 125, 122"),
      labeledCard(122, "NEXT(ROW, COL) = 0"),
      card("GO TO 140"),
      labeledCard(125, "NEXT(ROW, COL) = 1"),
      labeledCard(140, "CONTINUE"),
      labeledCard(150, "CONTINUE"),
      card("DO 170 ROW = 1, 6"),
      card("DO 160 COL = 1, 6"),
      card("GRID(ROW, COL) = NEXT(ROW, COL)"),
      labeledCard(160, "CONTINUE"),
      labeledCard(170, "CONTINUE"),
      labeledCard(200, "CONTINUE"),
      card("WRITE(6, 210)"),
      labeledCard(210, "FORMAT(18HFINAL GENERATION 4)"),
      card("DO 230 ROW = 1, 6"),
      card("WRITE(6, 220) (GRID(ROW, COL), COL = 1, 6)"),
      labeledCard(220, "FORMAT(1X, 6I3)"),
      labeledCard(230, "CONTINUE"),
      card("WRITE(6, 240)"),
      labeledCard(240, "FORMAT(14HEND SIMULATION)"),
      card("STOP"),
      card("END"),
      "/*",
      "//LKED.SYSLMOD DD DSN=&&GOSET(GO),DISP=(MOD,PASS)",
      "//GO     EXEC  PGM=*.LKED.SYSLMOD",
      "//GO.FT06F001 DD SYSOUT=A",
      "//GO.SYSIN   DD *",
      "C     TEST RUN PARAMETERS",
      "C     GRID DIMENSION 6X6 VERIFIED",
      "C     INITIAL CELL AT ROW 3 COL 4",
      "C     INITIAL CELL AT ROW 4 COL 4",
      "C     INITIAL CELL AT ROW 5 COL 4",
      "C     OSCILLATOR PERIOD EQUALS 2",
      "C     TIME LIMIT 0.40 SECONDS",
      "C     REGION SIZE 128K",
      "C     DEFAULT FORTRAN IV G COMPILER",
      "C     OUTPUT DESTINATION LINE PRINTER UNIT 6",
      "C     TRACK IDENTIFIER CSSS LEGACY 1973",
      "C     SFU COMPUTING CENTRE SUBMISSION",
      "C     BURNABY MOUNTAIN FACILITY",
      "C     IBM SYSTEM 370 MODEL 155",
      "C     COMPLETED CARD DECK TRAYS 1 AND 2",
      "C     CHECK DIAGONAL STRIPE INTEGRITY",
      "C     NO BATCH INTERRUPT REQUESTED",
      "C     RETURN CODE ZERO EXPECTED",
      "C     NORMAL TERMINATION REGISTERED",
      "C     CMPT 101 PRACTICUM FINAL CHALLENGE",
      "C     MASTER CERTIFICATION LEVEL 11",
      "C     END OF CONTROL PARAMETERS",
      "/*",
      "//",
      "C     ARCHIVAL MASTER RUN COMPLETE",
    ],
    acceptedOutput: /END SIMULATION/m,
  },
];

export function getLevel(id: LevelId): LevelDefinition {
  const level = LEVELS.find((candidate) => candidate.id === id);
  if (!level) throw new Error(`Unknown level: ${id}`);
  return level;
}
